"""add_reports_table

Revision ID: 4780252b7cdd
Revises: 1a898958b72d
Create Date: 2026-02-16 00:24:53.214885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4780252b7cdd'
down_revision: Union[str, None] = '1a898958b72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('company_id', sa.String(length=26), nullable=False),
    sa.Column('requested_by', sa.String(length=26), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_company_created', 'reports', ['company_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_company_created', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
