"""add_satisfaction_rating_to_support_tickets

Revision ID: 540ee94fe733
Revises: a925b41442dd
Create Date: 2026-03-04 12:12:28.866345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540ee94fe733'
down_revision: Union[str, None] = 'a925b41442dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('satisfaction_rating', sa.Integer(), nullable=True))
    op.add_column('support_tickets', sa.Column('satisfaction_comment', sa.Text(), nullable=True))
    op.add_column('support_tickets', sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'rated_at')
    op.drop_column('support_tickets', 'satisfaction_comment')
    op.drop_column('support_tickets', 'satisfaction_rating')
    # ### end Alembic commands ###
