"""

Revision ID: 89a311afa455
Revises: e55f2a001
Create Date: 2026-03-03 23:39:10.872598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89a311afa455'
down_revision: Union[str, None] = 'e55f2a001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_appointments_scheduled_start', table_name='appointments')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.alter_column('asset_checkouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('asset_type_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('asset_type_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_assets_criticality', table_name='assets', postgresql_where='(criticality IS NOT NULL)')
    op.alter_column('availability_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_overrides_technician_date', table_name='availability_overrides')
    op.create_index(op.f('ix_availability_overrides_company_id'), 'availability_overrides', ['company_id'], unique=False)
    op.create_index(op.f('ix_availability_overrides_technician_id'), 'availability_overrides', ['technician_id'], unique=False)
    op.alter_column('change_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('checklist_item_definitions_template_id_fkey', 'checklist_item_definitions', type_='foreignkey')
    op.drop_index('ix_ci_relationships_source', table_name='ci_relationships')
    op.drop_index('ix_ci_relationships_target', table_name='ci_relationships')
    op.create_index(op.f('ix_ci_relationships_source_asset_id'), 'ci_relationships', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_ci_relationships_target_asset_id'), 'ci_relationships', ['target_asset_id'], unique=False)
    op.drop_constraint('uq_companies_slug', 'companies', type_='unique')
    op.drop_index('ix_companies_slug', table_name='companies')
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.alter_column('company_assignment_ai_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_classification_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_procurement_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_sla_escalation_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_sla_escalation_config_company', table_name='company_sla_escalation_configs')
    op.create_index(op.f('ix_company_sla_escalation_configs_company_id'), 'company_sla_escalation_configs', ['company_id'], unique=False)
    op.alter_column('company_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('department_budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('equipment_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_checklist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_maintenance_plans_template_asset_active', table_name='maintenance_plans')
    op.alter_column('maintenance_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_maintenance_records_company_status', table_name='maintenance_records')
    op.create_index(op.f('ix_maintenance_records_source_type'), 'maintenance_records', ['source_type'], unique=False)
    op.alter_column('maintenance_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_maintenance_templates_company_active', table_name='maintenance_templates')
    op.alter_column('post_implementation_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_pir_change_request_id', table_name='post_implementation_reviews')
    op.alter_column('purchase_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_purchase_orders_status', table_name='purchase_orders')
    op.alter_column('request_checklist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('request_checklist_items_request_id_fkey', 'request_checklist_items', type_='foreignkey')
    op.drop_index('ix_reseller_clients_demo_expires', table_name='reseller_clients', postgresql_where='(is_demo = true)')
    op.drop_constraint('resellers_email_key', 'resellers', type_='unique')
    op.drop_constraint('resellers_google_id_key', 'resellers', type_='unique')
    op.drop_constraint('resellers_microsoft_id_key', 'resellers', type_='unique')
    op.drop_constraint('resellers_referral_code_key', 'resellers', type_='unique')
    op.drop_index('ix_resellers_email', table_name='resellers')
    op.create_index(op.f('ix_resellers_email'), 'resellers', ['email'], unique=True)
    op.drop_index('ix_resellers_google_id', table_name='resellers')
    op.create_index(op.f('ix_resellers_google_id'), 'resellers', ['google_id'], unique=True)
    op.drop_index('ix_resellers_microsoft_id', table_name='resellers')
    op.create_index(op.f('ix_resellers_microsoft_id'), 'resellers', ['microsoft_id'], unique=True)
    op.drop_index('ix_resellers_referral_code', table_name='resellers')
    op.create_index(op.f('ix_resellers_referral_code'), 'resellers', ['referral_code'], unique=True)
    op.drop_index('ix_service_requests_workflow_template', table_name='service_requests')
    op.alter_column('shipment_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_shipments_direction', table_name='shipments')
    op.drop_index('ix_shipments_status', table_name='shipments')
    op.alter_column('shipping_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sla_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sla_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('technician_availabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_tech_availabilities_technician', table_name='technician_availabilities')
    op.create_index(op.f('ix_technician_availabilities_company_id'), 'technician_availabilities', ['company_id'], unique=False)
    op.create_index(op.f('ix_technician_availabilities_technician_id'), 'technician_availabilities', ['technician_id'], unique=False)
    op.drop_constraint('uq_users_google_id', 'users', type_='unique')
    op.drop_constraint('uq_users_microsoft_id', 'users', type_='unique')
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_index('ix_users_microsoft_id', table_name='users')
    op.create_index(op.f('ix_users_microsoft_id'), 'users', ['microsoft_id'], unique=True)
    op.alter_column('vendor_dependencies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_risk_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('workflow_subtypes_template_id_fkey', 'workflow_subtypes', type_='foreignkey')
    op.alter_column('workflow_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('workflow_templates_company_id_fkey', 'workflow_templates', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('workflow_templates_company_id_fkey', 'workflow_templates', 'companies', ['company_id'], ['id'])
    op.alter_column('workflow_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('workflow_subtypes_template_id_fkey', 'workflow_subtypes', 'workflow_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_risk_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_dependencies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_microsoft_id'), table_name='users')
    op.create_index('ix_users_microsoft_id', 'users', ['microsoft_id'], unique=False)
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.create_unique_constraint('uq_users_microsoft_id', 'users', ['microsoft_id'])
    op.create_unique_constraint('uq_users_google_id', 'users', ['google_id'])
    op.drop_index(op.f('ix_technician_availabilities_technician_id'), table_name='technician_availabilities')
    op.drop_index(op.f('ix_technician_availabilities_company_id'), table_name='technician_availabilities')
    op.create_index('ix_tech_availabilities_technician', 'technician_availabilities', ['technician_id'], unique=False)
    op.alter_column('technician_availabilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sla_policies', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sla_policies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shipping_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_shipments_status', 'shipments', ['status'], unique=False)
    op.create_index('ix_shipments_direction', 'shipments', ['direction'], unique=False)
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shipment_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_service_requests_workflow_template', 'service_requests', ['workflow_template_id'], unique=False)
    op.drop_index(op.f('ix_resellers_referral_code'), table_name='resellers')
    op.create_index('ix_resellers_referral_code', 'resellers', ['referral_code'], unique=False)
    op.drop_index(op.f('ix_resellers_microsoft_id'), table_name='resellers')
    op.create_index('ix_resellers_microsoft_id', 'resellers', ['microsoft_id'], unique=False)
    op.drop_index(op.f('ix_resellers_google_id'), table_name='resellers')
    op.create_index('ix_resellers_google_id', 'resellers', ['google_id'], unique=False)
    op.drop_index(op.f('ix_resellers_email'), table_name='resellers')
    op.create_index('ix_resellers_email', 'resellers', ['email'], unique=False)
    op.create_unique_constraint('resellers_referral_code_key', 'resellers', ['referral_code'])
    op.create_unique_constraint('resellers_microsoft_id_key', 'resellers', ['microsoft_id'])
    op.create_unique_constraint('resellers_google_id_key', 'resellers', ['google_id'])
    op.create_unique_constraint('resellers_email_key', 'resellers', ['email'])
    op.create_index('ix_reseller_clients_demo_expires', 'reseller_clients', ['demo_expires_at'], unique=False, postgresql_where='(is_demo = true)')
    op.create_foreign_key('request_checklist_items_request_id_fkey', 'request_checklist_items', 'service_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.alter_column('request_checklist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.alter_column('purchase_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_pir_change_request_id', 'post_implementation_reviews', ['change_request_id'], unique=False)
    op.alter_column('post_implementation_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_maintenance_templates_company_active', 'maintenance_templates', ['company_id', 'is_active'], unique=False)
    op.alter_column('maintenance_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_maintenance_records_source_type'), table_name='maintenance_records')
    op.create_index('ix_maintenance_records_company_status', 'maintenance_records', ['company_id', 'status'], unique=False)
    op.alter_column('maintenance_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_maintenance_plans_template_asset_active', 'maintenance_plans', ['template_id', 'asset_id', 'is_active'], unique=False)
    op.alter_column('maintenance_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_checklist_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_roles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('employee_roles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('department_budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_company_sla_escalation_configs_company_id'), table_name='company_sla_escalation_configs')
    op.create_index('ix_sla_escalation_config_company', 'company_sla_escalation_configs', ['company_id'], unique=False)
    op.alter_column('company_sla_escalation_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_procurement_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_classification_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_assignment_ai_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.create_index('ix_companies_slug', 'companies', ['slug'], unique=False)
    op.create_unique_constraint('uq_companies_slug', 'companies', ['slug'])
    op.drop_index(op.f('ix_ci_relationships_target_asset_id'), table_name='ci_relationships')
    op.drop_index(op.f('ix_ci_relationships_source_asset_id'), table_name='ci_relationships')
    op.create_index('ix_ci_relationships_target', 'ci_relationships', ['target_asset_id'], unique=False)
    op.create_index('ix_ci_relationships_source', 'ci_relationships', ['source_asset_id'], unique=False)
    op.create_foreign_key('checklist_item_definitions_template_id_fkey', 'checklist_item_definitions', 'workflow_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.alter_column('change_requests', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('change_requests', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('change_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_availability_overrides_technician_id'), table_name='availability_overrides')
    op.drop_index(op.f('ix_availability_overrides_company_id'), table_name='availability_overrides')
    op.create_index('ix_overrides_technician_date', 'availability_overrides', ['technician_id', 'date'], unique=False)
    op.alter_column('availability_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_assets_criticality', 'assets', ['criticality'], unique=False, postgresql_where='(criticality IS NOT NULL)')
    op.alter_column('asset_type_definitions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('asset_type_definitions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('asset_checkouts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_scheduled_start', 'appointments', ['scheduled_start'], unique=False)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
