"""

Revision ID: a925b41442dd
Revises: 1ab4e919b5fa
Create Date: 2026-03-04 08:41:19.512511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a925b41442dd'
down_revision: Union[str, None] = '1ab4e919b5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create sequence for ticket reference numbers (SUP-NNNN)
    op.execute("CREATE SEQUENCE support_ticket_ref_seq START 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.String(length=26), nullable=False),
    sa.Column('created_by', sa.String(length=26), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='open', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('ai_conversation_summary', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_support_tickets_company_status', 'support_tickets', ['company_id', 'status'], unique=False)
    op.create_index('ix_support_tickets_created_by', 'support_tickets', ['company_id', 'created_by'], unique=False)
    op.create_index('ix_support_tickets_status_priority', 'support_tickets', ['status', 'priority'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.String(length=26), nullable=False),
    sa.Column('author_id', sa.String(length=26), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_from_platform', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_messages_ticket_id', 'ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_messages_ticket_id', table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index('ix_support_tickets_status_priority', table_name='support_tickets')
    op.drop_index('ix_support_tickets_created_by', table_name='support_tickets')
    op.drop_index('ix_support_tickets_company_status', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.execute("DROP SEQUENCE IF EXISTS support_ticket_ref_seq")
    # ### end Alembic commands ###
