"""add_company_status_and_email_domains

Revision ID: bc5eab61e74b
Revises: ec75f2a503c6
Create Date: 2026-02-15 17:00:54.728766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5eab61e74b'
down_revision: Union[str, None] = 'ec75f2a503c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_email_domains',
    sa.Column('company_id', sa.String(length=26), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_email_domains_company_id'), 'company_email_domains', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_email_domains_domain'), 'company_email_domains', ['domain'], unique=True)
    op.add_column('companies', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'status')
    op.drop_index(op.f('ix_company_email_domains_domain'), table_name='company_email_domains')
    op.drop_index(op.f('ix_company_email_domains_company_id'), table_name='company_email_domains')
    op.drop_table('company_email_domains')
    # ### end Alembic commands ###
