"""add_service_requests_and_related_tables

Revision ID: dfae9268fd2d
Revises: f8a1bff4afbd
Create Date: 2026-02-15 21:10:32.845131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfae9268fd2d'
down_revision: Union[str, None] = 'f8a1bff4afbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('company_id', sa.String(length=26), nullable=False),
    sa.Column('created_by', sa.String(length=26), nullable=False),
    sa.Column('assigned_to', sa.String(length=26), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='submitted', nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_requests_company_assigned_to', 'service_requests', ['company_id', 'assigned_to'], unique=False)
    op.create_index('ix_service_requests_company_created_by', 'service_requests', ['company_id', 'created_by'], unique=False)
    op.create_index('ix_service_requests_company_status', 'service_requests', ['company_id', 'status'], unique=False)
    op.create_table('request_comments',
    sa.Column('request_id', sa.String(length=26), nullable=False),
    sa.Column('author_id', sa.String(length=26), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_comments_request_id'), 'request_comments', ['request_id'], unique=False)
    op.create_table('request_events',
    sa.Column('request_id', sa.String(length=26), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('performed_by', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_events_request_id'), 'request_events', ['request_id'], unique=False)
    op.create_table('request_notes',
    sa.Column('request_id', sa.String(length=26), nullable=False),
    sa.Column('author_id', sa.String(length=26), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_notes_request_id'), 'request_notes', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_notes_request_id'), table_name='request_notes')
    op.drop_table('request_notes')
    op.drop_index(op.f('ix_request_events_request_id'), table_name='request_events')
    op.drop_table('request_events')
    op.drop_index(op.f('ix_request_comments_request_id'), table_name='request_comments')
    op.drop_table('request_comments')
    op.drop_index('ix_service_requests_company_status', table_name='service_requests')
    op.drop_index('ix_service_requests_company_created_by', table_name='service_requests')
    op.drop_index('ix_service_requests_company_assigned_to', table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
