from enum import Enum


class EventType(str, Enum):
    REQUEST_CREATED = "request.created"
    REQUEST_STATUS_CHANGED = "request.status_changed"
    REQUEST_ASSIGNED = "request.assigned"
    REQUEST_PRIORITY_CHANGED = "request.priority_changed"
    REQUEST_COMMENT_ADDED = "request.comment_added"
    REQUEST_NOTE_ADDED = "request.note_added"
    REQUEST_APPROVAL_NEEDED = "request.approval_needed"
    REQUEST_APPROVED = "request.approved"
    REPORT_READY = "report.ready"
    PO_SUBMITTED = "po.submitted"
    PO_APPROVED = "po.approved"
    PO_CANCELLED = "po.cancelled"
    BUDGET_THRESHOLD_REACHED = "budget.threshold_reached"
    PO_RECEIVED = "po.received"
    APPOINTMENT_CREATED = "appointment.created"
    APPOINTMENT_CONFIRMED = "appointment.confirmed"
    APPOINTMENT_CANCELLED = "appointment.cancelled"
    APPOINTMENT_RESCHEDULED = "appointment.rescheduled"
    APPOINTMENT_COMPLETED = "appointment.completed"
    APPOINTMENT_REMINDER = "appointment.reminder"
    SHIPMENT_CREATED = "shipment.created"
    SHIPMENT_DISPATCHED = "shipment.dispatched"
    SHIPMENT_DELIVERED = "shipment.delivered"
    SHIPMENT_FAILED = "shipment.failed"
    SHIPMENT_CANCELLED = "shipment.cancelled"
    MAINTENANCE_SCHEDULED = "maintenance.scheduled"
    MAINTENANCE_DUE = "maintenance.due"
    MAINTENANCE_OVERDUE = "maintenance.overdue"
    MAINTENANCE_COMPLETED = "maintenance.completed"
    MAINTENANCE_CANCELLED = "maintenance.cancelled"
